import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

// Components
import Header from "../components/layout/Header";

const switzerFont = localFont({
  src: "../fonts/Switzer-Variable.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${switzerFont.className} antialiased min-h-[125vh]`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
